version: "3.8"

services:
  whatsapp-whisperai:
    container_name: whatsapp_whisperai
    image: whatsapp_whisperai
    build: .
    restart: always
    ports:
      - 7729:7729
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
